<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>
<script>
    /*
    * js中的报错机制
    *再JS中使用 catch 来捕获报错信息，try中方如执行的代码，如果带有报错，通过catch中的参数e来进行接收
    * 如果没有报错不会执行catch内容
    * finally 报错与不报错都会执行
    *
    *
    * throw new Error('报错的内容') 手动抛出一个报错信息
    * */
    try{
        function fn() {
            fn()
        };
        fn()
    }catch (e){
        throw new RangeError console.log(e);
        console.log(1);
    }finally {
        console.log(2);
    }
    ('xinxi');
    console.log(3);
</script>